config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :accounts }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  post 'pages', to: 'pages#create'
  resources :checkout

  scope 'my-account' do
    resources :cards
    get 'profile', to: 'accounts#edit'
  end
  namespace :admin do
    resources :users
  end
end

app/models/Card.rb
class Card
  include ActiveModel::Model

  attr_accessor :card_name, :card_number, :card_cvc, :card_expires_month, :card_expires_year

  validates :card_name, presence: true
  validates :card_expires_month, presence: true
  validates :card_expires_year, presence: true

  def self.month_options
    Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i + 1]}
  end

  def self.year_options
    (Date.today.year..(Date.today.year+20)).to_a
  end

end

app/models/Payment.rb
class Payment < ApplicationRecord
  belongs_to :user

  def process_payment(customer_id, card_id = nil)
    charge = Stripe::Charge.create(
      amount: amount,
      currency: 'gbp',
      customer: customer_id,
      source: card_id,
      description: 'Some amazing product'
    )
    self.token = charge.id
  end
end

app/models/admin_user.rb
class AdminUser < User

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :payments

  def admin?
    admin_types.include?(type)
  end

  private

  def admin_types
    ['AdminUser']
  end
end

app/controllers/accounts_controller.rb
class AccountsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:forename, :surname])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception, prepend: true
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_customer, only: [:edit, :update, :destroy]

  def index
    if current_user.customer_id.present?
      @cards = Stripe::Customer.retrieve(current_user.customer_id).sources.all(object: 'card')
    else
      @cards = nil
    end
  end

  def create
    customer = Stripe::Customer.retrieve(current_user.customer_id)
    begin
      customer.sources.create(source: params[:stripeToken])
      flash[:success] = 'Card successfully added to your account'
      redirect_to cards_path(current_user)
    rescue
      flash[:error] = 'Card could not be added to your account'
      render :new
    end
  end

  def new
    unless current_user.customer_id.present?
      customer = Stripe::Customer.create(
        email: current_user.email,
        source: params[:stripeToken]
      )
      current_user.customer_id = customer.id
      current_user.save
    end
  end

  def edit
    @card = Card.new
    @card_info = @customer.sources.retrieve(params[:id])
  end

  def update
    @card = Card.new(card_params)
    if @card.valid?
      card = @customer.sources.retrieve(params[:id])
      card.name = card_params[:card_name]
      card.exp_month = card_params[:card_expires_month]
      card.exp_year = card_params[:card_expires_year]
      begin
        card.save
        flash[:success] = 'Card details have been successfully updated'
        redirect_to cards_path
      rescue
        flash[:error] = 'Card details could not be updated'
        redirect_to edit_card_path(card.id)
      end
    end
  end

  def destroy
    respond_to do |format|
      begin
        @customer.sources.retrieve(params[:id]).delete
        format.json { redirect_to cards_path(current_user) }
      rescue
        format.json { render json: { success: true }, status: 400 }
      end

    end
  end

  private

  def set_customer
    @customer = Stripe::Customer.retrieve(current_user.customer_id)
  end

  def card_params
    params.require(:card).permit(
      :card_name, :card_expires_month, :card_expires_year
    )
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :get_customer, only: :create

  def index
    if current_user.customer_id.present?
      @cards = Stripe::Customer.retrieve(current_user.customer_id).sources.all(object: 'card')
    else
      @cards = nil
    end
  end

  def create
    amount = 30
    if params[:cards].present?
      card_id = params[:cards]
    else
      card_id = @customer.sources.create(source: params[:stripeToken]).id
    end

    payment = Payment.new(amount: amount, user: current_user)
    begin
      payment.process_payment(@customer_id, card_id)
      flash[:success] = 'Success - Payment Received'
      payment.save
    rescue Exception => e
      flash[:alert] = e.message
    end

    redirect_to checkout_index_path
  end

  private

  def get_customer
    if current_user.customer_id.nil?
      @customer = Stripe::Customer.create(
        email: current_user.email,
        source: params[:stripeToken]
      )
      @customer_id = @customer.id
    else
      @customer_id = current_user.customer_id
      @customer = Stripe::Customer.retrieve(@customer_id)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    authorize User
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/edit.html.erb
<%= bootstrap_devise_error_messages! %>
<div class="panel panel-default devise-bs">
  <div class="panel-heading">
    <h4><%= t('.title', resource: resource_class.model_name.human , default: "Edit #{resource_name.to_s.humanize}") %></h4>
  </div>
  <div class="panel-body">
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
      <div class="form-group">
        <%= f.label :forename %>
        <%= f.text_field :forename, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :surname %>
        <%= f.text_field :surname, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password %> <i>(<%= t('.leave_blank_if_you_don_t_want_to_change_it', default: "leave blank if you don't want to change it") %>)</i>
        <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control'  %>
      </div>
      <div class="form-group">
        <%= f.label :current_password %> <i>(<%= t('.we_need_your_current_password_to_confirm_your_changes', default: 'we need your current password to confirm your changes') %>)</i>
        <%= f.password_field :current_password, class: 'form-control' %>
      </div>
      <%= f.submit t('.update', default: 'Update'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<p><%= t('.unhappy', default: 'Unhappy') %>? <%= link_to t('.cancel_my_account', default: 'Cancel my account'), registration_path(resource_name), data: { confirm: t('.are_you_sure', default: "Are you sure?") }, method: :delete %>.</p>

<%= link_to t('.back', default: 'Back'), :back %>

app/views/cards/edit.html.erb
<h1>Update Card Info</h1>
<%= form_for @card, url: card_path(@card_info.id), method: :put, html: { id: "edit-payment-form" } do |f| %>
  <input type="hidden" id="stripe_pub_key" value="<%= ENV['STRIPE_TEST_PUBLISHABLE_KEY'] %>">
  <div class="row">
    <div class="col-md-12 form-group">
      Payment Method: <i class="fa fa-cc-<%= @card_info.brand.downcase %>"></i> **** **** **** <%= @card_info.last4 %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.text_field :card_name, required: true, class: 'form-control', value: @card_info.name %>
    </div>

    <div class="col-md-2">
      <%= f.select :card_expires_month, options_for_select(Card.month_options, @card_info.exp_month),
                   { include_blank: 'Month' }, "data-stripe" => "exp-month",
                     class: "form-control", required: true

      %>
    </div>
    <div class="col-md-2">
      <%= f.select :card_expires_year, options_for_select(Card.year_options, @card_info.exp_year),
                   { include_blank: 'Year' }, "data-stripe" => "exp-year",
                     class: "form-control", required: true
      %>
    </div>

    <div class="col-md-2">
      <button class="btn btn-primary">Update Card</button>
    </div>

    <!-- Used to display form errors. -->
    <div id="card-errors" role="alert"></div>
  </div>
<% end %>

app/views/cards/index.html.erb
<h1>My Cards</h1>
<p><%= link_to 'Register Card', new_card_path, class: 'btn btn-default', data: { turbolinks: false } %></p>
<% unless @cards.nil? %>
<div class="row">
  <div class="col-md-6">
    <% @cards.each do |card| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-cc-<%= card.brand.downcase %>"></i>
        **** **** **** <%= card.last4 %> Exp: <%= card.exp_month %>/<%= card.exp_year %>
        <a class="pull-right" data-toggle="collapse" href="#<%= card.id %>">
          <span class="glyphicon glyphicon-chevron-down pull-right">
        </span>
        </a>
      </div>
      <div id="<%= card.id %>" class="panel-collapse collapse">
        <div class="panel-body">
          <div class="col-md-5">
            <strong>Name on Card:</strong><br>
            <%= card.name %>
          </div>
          <div class="col-md-7">
            <%= card.inspect %>
          </div>
        </div>
        <div class="panel-footer text-right">
          <%= link_to 'Edit', edit_card_path(card.id), class: 'btn btn-default', data: { turbolinks: false } %>
          <%= link_to 'Delete', card_path(card.id),
                      method: :delete, remote: true,
                      data: { confirm: 'Are you sure you wish to delete this card?' }, class: 'btn btn-default' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<% end %>

app/views/cards/new.html.erb
<div data-turbolinks="false">
<h1>Register New Card</h1>
<%= form_tag cards_path, id: "payment-form" do %>
    <input type="hidden" id="stripe_pub_key" value="<%= ENV['STRIPE_TEST_PUBLISHABLE_KEY'] %>">
    <div class="form-row row">
      <div class="col-md-4">
        <input type="text" class="form-control" name="card_name" id="card_name" placeholder="Name on Card" required="true">
      </div>
      <div class="col-md-5">

        <div id="card-element" class="form-control">
          <!-- A Stripe Element will be inserted here. -->
        </div>

      </div>
      <div class="col-md-3">
        <button class="btn btn-primary">Add Card</button>
      </div>

      <!-- Used to display form errors. -->
      <div id="card-errors" role="alert"></div>
    </div>
<% end %>
</div>

app/views/checkout/index.html.erb
<div data-turbolinks="false">
<h1>Checkout</h1>
  <div class="row">
    <div class="col-md-9">
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#addressPanel" aria-expanded="false" aria-controls="collapseOne">
                Address
              </a>
            </h4>
          </div>
          <div id="addressPanel" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
              3 Cotter Riggs Walk<br>
              Chapel House<br>
              Newcastle upon Tyne<br>
              NE5 1HH
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#deliveryPanel" aria-expanded="false" aria-controls="collapseOne">
                Delivery
              </a>
            </h4>
          </div>
          <div id="deliveryPanel" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
              Free Delivery
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#paymentPanel" aria-expanded="true" aria-controls="collapseOne">
                Payment
              </a>
            </h4>
          </div>
          <div id="paymentPanel" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">



              <%= form_tag checkout_index_path, id: "payment-form" do %>
                <% unless @cards.nil? %>
                  <div class="form-row" id="existing_card_payment">
                    <div class="form-group">
                      <label for="cards">My Cards</label>
                      <select name="cards" id="card_select" class="form-control">
                        <option value="">Select a Card</option>
                        <% @cards.each do |card| %>
                          <option value="<%= card.id %>">
                            **** **** **** <%= card.last4 %> Exp: <%= card.exp_month %>/<%= card.exp_year %>
                          </option>
                        <% end %>
                      </select>
                    </div>
                  </div>
                <% end %>

                <input type="hidden" id="stripe_pub_key" value="<%= ENV['STRIPE_TEST_PUBLISHABLE_KEY'] %>">
                <div class="form-row" id="new_card_payment">
                  <div class="form-group">
                    <div class="row">
                      <div class="col-md-5">
                        <input type="text" class="form-control" name="card_name" id="card_name" placeholder="Name on Card" required="true">
                      </div>
                      <div class="col-md-7">

                        <div id="card-element" class="form-control">
                          <!-- A Stripe Element will be inserted here. -->
                        </div>

                      </div>
                    </div>
                    <div class="col-md-12">

                    </div>

                    <!-- Used to display form errors. -->
                    <div id="card-errors" role="alert"></div>
                  </div>
                </div>


                <div class="form-row">
                  <button class="btn btn-primary">Pay</button>
                </div>
              <% end %>
              <hr>
              <div class="form-row row">
                <div class="col-md-6">
                  <div id="payment-request-button">

                  </div>
                </div>
              </div>



            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3">

      <div class="panel panel-default">
        <div class="panel-body">
          <p>Basket Preview</p>
          <ul>
            <li>Goes</li>
            <li>Here</li>
            <li>in</li>
            <li>this</li>
            <li>side</li>
            <li>panel</li>
          </ul>
        </div>
        <div class="panel-footer">Total: £25.99</div>
      </div>

      <h3></h3>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Marketplace" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_include_tag "https://js.stripe.com/v3" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Marketplace</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'Checkout', checkout_index_path %>
            </li>
          </ul>
          <% if user_signed_in? && current_user.admin? %>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Users', admin_users_path %></a></li>
                <li><a href="#">Companies</a></li>
                <li><a href="#">Payments</a></li>
              </ul>
            </li>
          </ul>
            <% end %>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Account<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Your Profile", edit_user_registration_path %></li>
                  <li><%= link_to "My Cards", cards_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else%>
              <li><%= link_to 'Login', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <% end %>

          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/index.html.erb
<h1>Hello World</h1>

app/views/users/index.html.erb
<h1>List Users</h1>
<%= @users.inspect %>